### PR TITLE
Initialize provider console workspace

### PR DESCRIPTION
**Pull request by jigar-arc10**
- Initialization of React App

### CODE REVIEW

**Comment by baktun14** [comment]
Great! You should setup tailwind as well.

**Comment by jigar-arc10** [comment]
> Great! You should setup tailwind as well.

This is WIP and will work on adding more stuff like tailwind, router and other imp libraries.

**Comment by ygrishajev** [comment]
May I ask why cra? Afaik it's got issues and there are better alternatives.

Some top googling items

https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295

https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o

For this reason I picked vite on my previous project.

And it seems that maintainers dropped it support indeed. Last commit 1y ago.

Also having exp working with both I can add that cra development is really slow once the project grows. It's harder to customize and ejection is needed pretty soon quite often. Vite was a breeze after it.

**Comment by jigar-arc10** [comment]
> May I ask why cra? Afaik it's got issues and there are better alternatives.
> 
> Some top googling items
> 
> https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295
> 
> https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
> 
> For this reason I picked vite on my previous project.
> 
> And it seems that maintainers dropped it support indeed. Last commit 1y ago

I debated Vite vs. Cra, and React docs don't have Vite in them (that's why I chose Cra). There were other tools like Remix and Gatsby, but I didn't get convinced; that's why I chose Cra. I didn't have any experience with Vite. But we can switch; it's a no-brainer. @baktun14, your input?

**Comment by baktun14** [comment]
> > Great! You should setup tailwind as well.
> 
> This is WIP and will work on adding more stuff like tailwind, router and other imp libraries.

Can you change the status of the pr to draft then please

**Comment by baktun14** [comment]
> > May I ask why cra? Afaik it's got issues and there are better alternatives.
> > Some top googling items
> > https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295
> > https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
> > For this reason I picked vite on my previous project.
> > And it seems that maintainers dropped it support indeed. Last commit 1y ago
> 
> I debated Vite vs. Cra, and React docs don't have Vite in them (that's why I chose Cra). There were other tools like Remix and Gatsby, but I didn't get convinced; that's why I chose Cra. I didn't have any experience with Vite. But we can switch; it's a no-brainer. @baktun14, your input?

Agree that cra is not an attractive choice, espcially with the webpack config being abstracted and having to eject to change stuff. Preferably with nextjs for homogeneity with other projects in the repo, but I heard good things about vite.
image

**Comment by jigar-arc10** [comment]
> > > May I ask why cra? Afaik it's got issues and there are better alternatives.
> > > Some top googling items
> > > https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295
> > > https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
> > > For this reason I picked vite on my previous project.
> > > And it seems that maintainers dropped it support indeed. Last commit 1y ago
> > 
> > 
> > I debated Vite vs. Cra, and React docs don't have Vite in them (that's why I chose Cra). There were other tools like Remix and Gatsby, but I didn't get convinced; that's why I chose Cra. I didn't have any experience with Vite. But we can switch; it's a no-brainer. @baktun14, your input?
> 
> Agree that cra is not an attractive choice, espcially with the webpack config being abstracted and having to eject to change stuff. Preferably with nextjs for homogeneity with other projects in the repo, but I heard good things about vite. image

We can go with Nextjs so that it will be the same as other projects. It's just we might never use server-side features. @ygrishajev @baktun14?

**Comment by ygrishajev** [comment]
I personally like vite more. But I see a huge benefit in using same tech. It improves maintainability and delivery speed quite a bit. Like atm I'm working on docker and docker compose in a different PR. Using next you'd be able to solve ci and deployment with that already. Ofc it's not yet ideal but we'll be able to improve in bulk. Also other contributors will be more likely to onboard and understand codebase easier.

I think if u don't use ssr with next it's gonna be just fine. I'd just make sure that all the components are abstracted from pages so that they can be potentially used with react router. It's a really little overhead that would keep the door open for other possibilities just in case.

However we were just discussing with @Redm4x that ssr might be useful with env vars. so that they are not static but dynamic coming from ss props. This way we'd be able to build an image and run it with different envs as any other ba service.

**Comment by jigar-arc10** [comment]
So, we agree with the Nextjs setup. I will close this PR and create a new one with the Nextjs setup. Is that okay with everybody?

**Comment by baktun14** [comment]
> he door open for other possibilities just in case.

Makes sense to me!

**Pull request closed without merging**
