### PR TITLE
feat/update elements to v1.3.3

### PR DESCRIPTION
**Pull request by siddharthborderwala**
Update `@leapwallet/elements` to that latest version (v1.3.3)

It features UX updates as well as added support for Fiat on-ramp via Kado.

### CODE REVIEW

**Comment by baktun14** [comment]
Hey @siddharthborderwala, thanks for updating Elements. Is this ready to review?

**Comment by siddharthborderwala** [comment]
Hi @baktun14 it's ready to review.

**Comment by baktun14** [comment]
@siddharthborderwala I tested it locally and it looks good. There was some conflicts in the package-lock file that I resolved and rebased from main.

**Review by baktun14 — APPROVED** [review]

**Comment by baktun14** [comment]
I get this error when opening the modal, going somewhere in the app and coming back.
image

**Review by baktun14 — APPROVED** [review]

**Review by baktun14 — CHANGES_REQUESTED** [review]
See the error above

**Comment by siddharthborderwala** [comment]
@baktun14 I will check this out

**Comment by siddharthborderwala** [comment]
@baktun14 I'm not able to reproduce the error with the steps you have specified. Can you check again? It might have been a one-off error on the dev server.

**Comment by baktun14** [comment]
@siddharthborderwala I don't know how it happens, but I was able to reproduce it once. I changed wallet on the get started page and then created a deployment, then came back and had the error. There's also an hydration error when changing wallet. 
image

**Comment by siddharthborderwala** [comment]
@baktun14 The error you faced might be a one-off and it comes from Rainbowkit (ETH wallet adapter). If it happens again, we will look into it.

And for the hydration error, we are aware of the issue and will fix it in the coming releases. It won't affect the application.

We recommend going forward with v1.3.3 as it's the stable version with all latest features elements has to offer. We're even using it on [SwapFast](https://swapfast.app).

**Comment by baktun14** [comment]
> @baktun14 The error you faced might be a one-off and it comes from Rainbowkit (ETH wallet adapter). If it happens again, we will look into it.
> 
> And for the hydration error, we are aware of the issue and will fix it in the coming releases. It won't affect the application.
> 
> We recommend going forward with v1.3.3 as it's the stable version with all latest features elements has to offer. We're even using it on [SwapFast](https://swapfast.app).

Alright we'll do that. If I see the error again I will report back.

**Review by baktun14 — APPROVED** [review]

**Comment by siddharthborderwala** [comment]
Hi @baktun14, when will this PR be live on https://console.akash.network ?

**Comment by baktun14** [comment]
Hey @siddharthborderwala this week!

**Pull request merged**
